baseurl = 'https://clgithub.github.io/'
languageCode = 'zh-cn'
title = 'L'
theme = "hyde"


[params]
  description = "记录日常有趣事物，不管怎样，只是想把生命中有趣的事物、或是感悟或是思考记录下来，只有这种简单的文本格式的页面才是属于自己个人的，类型不限，可能有文字、视频、音频……，一个很早就有的想法，这是一个开始。"
  themeColor = "theme-base-0d"
  


# 自动检测语言并限制摘要字数
hasCJKLanguage = true
summaryLength = 70


# 自定义发布目录
publishDir="CLgithub.github.io"

params.dateFormat="2006-01-02"
params.style = "auto"

